### ISSUE TITLE
Is this correct output? 'data' or 'IS NOT A NUMBER'

### ISSUE THREAD

**Issue by sethleedy** [farhad2161/Randbit#10]
At first it was outputting 'IS NOT A NUMBER' between Thread-1 outputs. Change a few print calls and now it is 'data'.

![image](https://user-images.githubusercontent.com/11452198/235744535-3827ce55-83c7-42e5-9c39-64ce7c0e041c.png)

Sample output:

Thread-1,private:f7cae3bff71ec4c76c05cadcd71c080215d116fb00735713155fe0ec205a5a3b,wif:5KhR7HygV3LYxPyeKwxHDHUiocNpFpBAncksFnQXn7gKKj3M4eu,address:1MXtCgmcwuRgmbA3saXTxE41b2y1NGb3vN,balance:0
Thread-1,private:7a27e5ae9c651d8d8dc38e492ea8034657e0765a9097683a224a8e3df0246cf9,wif:5Jk5tVrzKXVoD94M7NndsVweqPeKQMDNvukq222bTFhYq7quwy5,address:1DaXNf4NtfRuSYfyDm6gbHkJaFh4AneD4P,balance:0
'data'
'data'
'data'
'data'
Thread-1,private:ac23eafe25c26c16c4c8797549634d7a42738ca627f2bf658158ca3aba31eee2,wif:5K86g5SRRNcyZzPhPdSsuuxBEGpJbeek9DqVUAD8GdaBKperSyP,address:16NJTb4QtoPQX7DekexHkJJAwN7MD8LwCM,balance:0
Thread-1,private:acddd9ee962a343ab52f5178e7b9922914ebd4dbbd1124713bc8371605c020a3,wif:5K8RE7m4dNAJpKiB9joTiNeMEYcb9kD5Pn2kS9ZQsYDoAqU4MYe,address:1Bjk7uq9fPdowNLj9k5MNMni3UzP9JGkVX,balance:0
Thread-1,private:b2367300a8978ec741f4db99e864c5c9b174352db72edc006221551fc81b5bf4,wif:5KAmnWqN7Z9NzQNbWFYPmnsm6YBSQye2mgJMgDNjxiLfGDiXs7A,address:1NbE2DQPdckRnkoV4tK4nX8bPWDEKRDr3R,balance:0
'data'
'data'
'data'
'data'

**Comment by sethleedy** [comment]
I am using the Blockchain.Info to get balance. Would this be because they are rate limiting my requests?

**Comment by farhad2161** [comment]
Yes it is probably because of rate limit.

Here is the blockchain.info api documentation: 
https://www.blockchain.com/explorer/api

And we are calling this api `addressbalance/$address` , you can read more about it here:
https://www.blockchain.com/explorer/api/q

**Comment by farhad2161** [comment]
Try to increase sleep time. You can find it in `bitnet.py` line 41 `time.sleep(1)`. Maybe a little improvement in `get_balance` method solves your problem. Do your best.
