### ISSUE TITLE
Strange log

### ISSUE THREAD

**Issue by PreWriter666** [farhad2161/Randbit#3]
Returns some strange answers if I use blockcypher.com
![sct](https://user-images.githubusercontent.com/72333417/95009174-04e1c080-0631-11eb-9a2d-1b69ebec2f60.png)

**Comment by PreWriter666** [comment]
And if I use blockchain.info
![str2](https://user-images.githubusercontent.com/72333417/95009204-4bcfb600-0631-11eb-89d5-eafe5a6ca2d1.png)

**Comment by farhad2161** [comment]
Hi,
You should check their API documentation. I guess they have changed their APIs a little bit.
I'm sure you can fix the problem by reading their API documentation.
Also remember that if you send too many request, they will block some of your requests.

Do not hesitate to send me a pull request ;)

**Comment by marissia** [comment]
hello, can you help me please why I see this message??   
 import configparser
ImportError: No module named configparser
what wrong I do?

**Comment by farhad2161** [comment]
Hi,
try this 
`pip install configparser`
then run again
