### ISSUE TITLE
don't work...

### ISSUE THREAD

**Issue by masikmos** [farhad2161/Randbit#5]
> # python3 main.py
> Thread-1 started!
> Thread-2 started!
> Thread-3 started!
> Thread-4 started!
> Thread-5 started!
> Thread-6 started!
> Thread-7 started!
> Thread-8 started!
> Thread-9 started!
> Thread-10 started!
> Thread-11 started!
> Thread-12 started!
> Thread-13 started!
> Thread-14 started!
> Thread-15 started!
> Thread-16 started!
> Thread-17 started!
> Thread-18 started!
> Thread-19 started!
> Thread-20 started!
> 'balance'
> 'balance'
> 'balance'
> 'balance'
> 'balance'
> 'balance'
> 'balance'
> 'balance'
> 'balance'
> 'balance'
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> Expecting value: line 2 column 1 (char 1)
> 'balance'
> 'balance'
> 'balance'

what she wont from me???

**Comment by masikmos** [comment]
oh i idiot sry, i rename **config.sample.ini** to **confige.ini**

**Comment by masikmos** [comment]
but now i hawe `NOT A NUMBER
NOT A NUMBER
NOT A NUMBER
NOT A NUMBER
NOT A NUMBER
NOT A NUMBER
NOT A NUMBER
NOT A NUMBER
NOT A NUMBER
NOT A NUMBER
NOT A NUMBER`

**Comment by farhad2161** [comment]
In your config.ini file, what is the value of `API_SITE` ?
I updated the code, pull and try again.
remember, when you send so many request, the api website will block you for a few seconds.
