### ISSUE TITLE
Thread Recommendation? 

### ISSUE THREAD

**Issue by LU5GOON** [farhad2161/Randbit#6]
How many threads do you recommend we set?
I get a lot of successful searches/tries at 15 (default)
But getting a lot of timeouts
Do you have a go to limit for better attempts with limited blocks/time outs?

Thank you

**Comment by farhad2161** [comment]
Hi
I guess 15 is good. Also you should adjust it according to the rate limit of web site which you call for getting wallet balance.
For example if you use blockchain.info , then you should check their api documentation to find out their api call limitation.

Have fun

**Comment by LU5GOON** [comment]
Thank you  @farhad2161 have you had much luck with findings of lost BTC with your tool here?

**Comment by farhad2161** [comment]
> Thank you @farhad2161 have you had much luck with findings of lost BTC with your tool here?

your welcome, unfortunately no.
