### ISSUE TITLE
Local Node

### ISSUE THREAD

**Issue by Tywors** [farhad2161/Randbit#7]
Hello, how can configure for check in local node?
thanks!

**Comment by farhad2161** [comment]
Hi,
You should modify `bitnet.py` file.
Modify this method `get_balance` like this
```
def get_balance(self, address):
  ...
  elif self.api_url == "localnode":
    result = self.get_balance_local_node(address)
  ...
```
Then add another method:

```
def get_balance_local_node(self, address):
  # Do what ever you need to get balance from your local node
```
And finally modify the config.ini like this:
```
API_SITE =localnode
```

Have fun
