### ISSUE TITLE
Missing WIF CHARACTERS

### ISSUE THREAD

**Issue by Handsomekaizer** [farhad2161/Randbit#8]
Hello sir
Sorry to bother I was just going through your repo to see if you could help me. The problem I have is with my wallet private key characters, I mistakenly damaged the piece of paper I wrote it on, so I was wondering if you could help me write a program that will brute Force the 10 missing characters very fast and in return I will make a donation of 2 BTC to you f I find the correct keys

**Comment by farhad2161** [comment]
Hi,
I will be very happy to help you find your key.
Do you have your public key? I think it will be very helpful.
Do you know the exact length of you private key?
We need to do some calculation to estimate how much will it take?

**Comment by Handsomekaizer** [comment]
Yes I have the public key and the WIF starts with L5 and 10 characters
after the L5 are missing. The total private key is 52 all I have is 42

**Comment by Noname400** [comment]
если у вас есть публичный ключ, советую посмотреть https://github.com/PawelGorny/Kangaroo
если необходимо я могу написать разработчику в телеграмм

**Comment by Handsomekaizer** [comment]
I have an idea is it possible for you to create a program maybe in html ,
JavaScript or typescript, go or php that fills in the missing characters in
the place there are missing (the place Missing will be marked ** or ??) And
the program will automatically generate millions of alphanumeric characters
and save it in form of txt that will be randomly checked to see if any of
the combination is correct or has balance.

**Comment by Noname400** [comment]
https://github.com/Noname400/wif-recovery
может подойдет

**Comment by farhad2161** [comment]
You have a WIF private key that uses Base58 encoding to encode the address.

Base58 is an encoding scheme with an alphabet of 58 characters, including upper and lowercase letters A-Z and the digits 1-9. Base58 excludes zero, uppercase ‘O’, uppercase ‘I’, and lowercase ‘l’, in order to avoid reader confusion.

So each character of your private key can be different 58 alphanumeric characters and you lost 10 characters: 
58 to the 10th power = 4.3080421e+17  
If you check 1000 private keys per second, it will takes about 13623387 years. 
It's a big number and I think your chance is close to zero.

Let me know if you found any solution.

**Comment by Noname400** [comment]
10 символов это 1 день пр. Наличии чексуммы

**Comment by farhad2161** [comment]
> 10 символов это 1 день пр. Наличии чексуммы

Google translate doesn't translate well. You have to write in English.

**Comment by Noname400** [comment]
it takes 1 day to find 10 characters.
assuming you know the last 6 characters

**Comment by Handsomekaizer** [comment]
> it takes 1 day to find 10 characters. assuming you know the last 6 characters

I have the last 6characters and I saw your code but cannot get it to run.
Can you run the code on https://repl.it/~ to see if it works

**Comment by Noname400** [comment]
https://github.com/Noname400/wif-recovery (Use if characters are missing not consecutively, but in different places)
https://github.com/PawelGorny/WifSolverCuda (Use if there is a checksum but no public key)
https://github.com/PawelGorny/Kangaroo (yes public key)

**Comment by farhad2161** [comment]
@Handsomekaizer 
I checked [@Noname400 ](https://github.com/Noname400/wif-recovery) suggested repository.
I can help you run it on your computer, I assume you are using windows:

1- Install python3 on your computer
2- Download the repository https://github.com/Noname400/wif-recovery/archive/refs/heads/main.zip
3- Unzip the file and run `cmd` where you unzipped it.
4- Run this command in cmd `python WIFRecover_successively.py -wif KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYv5Z9J7{1}{2}{3}{4}{5}{6}{7}11111`
5- If you get errors like `ModuleNotFoundError: No module named 'bitcoin'` , run this command `pip install bitcoin` and try again.

**Comment by Noname400** [comment]
better not to take from the archive
https://github.com/Noname400/wif-recovery/releases/tag/v2.1.0

**Comment by Handsomekaizer** [comment]
Ok thank you very much

**Comment by Noname400** [comment]
if you have any questions, you can ask me in the telegram
my telegram is listed on my github page
